name: Deploy Rails App for scuba diving repair with Docker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Rails App to Raspberry Pi using Docker and Passenger
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Raspberry Pi with Docker and Passenger
        env:
          RASPBERRY_PI_PASSWORD: ${{ secrets.RASPBERRY_PI_PASSWORD }}
          RASPBERRY_PI_IP: ${{ secrets.RASPBERRY_PI_IP }}
          SCUBADIVING_APP_DATABASE_NAME: ${{ secrets.SCUBADIVING_APP_DATABASE_NAME }}
          SCUBADIVING_APP_DATABASE_USER: ${{ secrets.SCUBADIVING_APP_DATABASE_USER }}
          SCUBADIVING_APP_DATABASE_PASSWORD: ${{ secrets.SCUBADIVING_APP_DATABASE_PASSWORD }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
        run: |
          sshpass -p $RASPBERRY_PI_PASSWORD ssh -o StrictHostKeyChecking=no pi@$RASPBERRY_PI_IP \
          "bash -s" << 'EOF'
          
            # Ensure Docker is installed
            if ! [ -x "$(command -v docker)" ]; then
              echo "Docker is not installed. Installing Docker..."
              curl -fsSL https://get.docker.com -o get-docker.sh
              sh get-docker.sh
            fi

            # Ensure Docker Compose is installed
            if ! [ -x "$(command -v docker-compose)" ]; then
              echo "Docker Compose is not installed. Installing Docker Compose..."
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.10.2/docker-compose-linux-armv7" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Remove the old app if it exists
            if [ -d "/var/www/html/scubadiving" ]; then
              echo "Removing old directory..."
              rm -rf /var/www/html/scubadiving
            fi

            # Clone the repository
            echo "Cloning repository..."
            git clone git@github.com:elviajero971/scuba_diving_repair.git /var/www/html/scubadiving

            # Change to the app directory
            cd /var/www/html/scubadiving

            # Set up environment variables
            echo "Setting up environment variables..."
            echo 'SCUBADIVING_APP_DATABASE_NAME=${SCUBADIVING_APP_DATABASE_NAME}' > .env.production
            echo 'SCUBADIVING_APP_DATABASE_USER=${SCUBADIVING_APP_DATABASE_USER}' >> .env.production
            echo 'SCUBADIVING_APP_DATABASE_PASSWORD=${SCUBADIVING_APP_DATABASE_PASSWORD}' >> .env.production
            echo 'SECRET_KEY_BASE=${SECRET_KEY_BASE}' >> .env.production

            # Dockerfile Build process
            echo "Building Docker images..."
            docker-compose down || true
            docker-compose build

            # Start the app and database using Docker Compose
            echo "Starting services with Docker Compose..."
            docker-compose up -d

            echo "Deployment complete."
          EOF
