name: Deploy Rails App with Nginx and PostgreSQL

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Rails App to Raspberry Pi with Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Raspberry Pi
        env:
          RASPBERRY_PI_PASSWORD: ${{ secrets.RASPBERRY_PI_PASSWORD }}
          RASPBERRY_PI_IP: ${{ secrets.RASPBERRY_PI_IP }}
        run: |
          sshpass -p $RASPBERRY_PI_PASSWORD ssh -o StrictHostKeyChecking=no pi@$RASPBERRY_PI_IP \
          "bash -s" << 'EOF'
            # Ensure Docker is installed
            if ! [ -x "$(command -v docker)" ]; then
              echo "Installing Docker..."
              curl -fsSL https://get.docker.com -o get-docker.sh
              sh get-docker.sh
            fi

            # Remove old containers
            docker-compose -f /path/to/docker-compose.yml down || true

            # Build and start new containers
            docker-compose -f /path/to/docker-compose.yml up -d --build

            echo "Deployment complete."
          EOF
