name: Deploy Rails App with Nginx
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker Image
        run: |
          docker buildx build \
            --platform linux/arm/v7 \
            --tag scubadiving-app:latest \
            --output type=docker,dest=image.tar .
      - name: Transfer Image to Raspberry Pi
        env:
          RASPBERRY_PI_PASSWORD: ${{ secrets.RASPBERRY_PI_PASSWORD }}
          RASPBERRY_PI_IP: ${{ secrets.RASPBERRY_PI_IP }}
        run: |
          sshpass -p $RASPBERRY_PI_PASSWORD scp -o ServerAliveInterval=120 -o ServerAliveCountMax=100 -o StrictHostKeyChecking=no image.tar pi@$RASPBERRY_PI_IP:/tmp/image.tar
          sshpass -p $RASPBERRY_PI_PASSWORD ssh -o ServerAliveInterval=120 -o ServerAliveCountMax=100 -o StrictHostKeyChecking=no pi@$RASPBERRY_PI_IP "docker load < /tmp/image.tar"
      - name: Deploy on Raspberry Pi
        env:
          RASPBERRY_PI_PASSWORD: ${{ secrets.RASPBERRY_PI_PASSWORD }}
          RASPBERRY_PI_IP: ${{ secrets.RASPBERRY_PI_IP }}
        run: |
          sshpass -p $RASPBERRY_PI_PASSWORD ssh -o ServerAliveInterval=120 -o ServerAliveCountMax=100 -o StrictHostKeyChecking=no pi@$RASPBERRY_PI_IP <<EOF
            cd /var/www/html/scubadiving
            docker-compose up -d --build
            docker-compose exec app bundle exec rake db:migrate
          EOF
