name: Deploy Rails App for scuba diving repair with Docker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Rails App to Raspberry Pi using Docker (without Apache)
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Raspberry Pi
        env:
          RASPBERRY_PI_PASSWORD: ${{ secrets.RASPBERRY_PI_PASSWORD }}
          RASPBERRY_PI_IP: ${{ secrets.RASPBERRY_PI_IP }}
          SCUBADIVING_APP_DATABASE_NAME: ${{ secrets.SCUBADIVING_APP_DATABASE_NAME }}
          SCUBADIVING_APP_DATABASE_USER: ${{ secrets.SCUBADIVING_APP_DATABASE_USER }}
          SCUBADIVING_APP_DATABASE_PASSWORD: ${{ secrets.SCUBADIVING_APP_DATABASE_PASSWORD }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
        run: |

          sshpass -p $RASPBERRY_PI_PASSWORD ssh -o StrictHostKeyChecking=no pi@$RASPBERRY_PI_IP \
          "bash -s" << 'EOF'
            # Ensure Docker is installed
            if ! [ -x "$(command -v docker)" ]; then
              echo "Docker is not installed. Installing Docker..."
              curl -fsSL https://get.docker.com -o get-docker.sh
              sh get-docker.sh
            fi

            # Ensure Docker Compose is installed
            if ! [ -x "$(command -v docker-compose)" ]; then
              echo "Docker Compose is not installed. Installing Docker Compose..."
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.10.2/docker-compose-linux-armv7" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Remove the old app if it exists
            if [ -d "/var/www/html/scubadiving" ]; then
              echo "Removing old directory..."
              rm -rf /var/www/html/scubadiving
            fi

            # Clone the repository
            echo "Cloning repository..."
            git clone git@github.com:elviajero971/scuba_diving_repair.git /var/www/html/scubadiving

            # Change to the app directory
            cd /var/www/html/scubadiving

            # Create .env file with the environment variables
            echo "SCUBADIVING_APP_DATABASE_NAME=$SCUBADIVING_APP_DATABASE_NAME" >> /var/www/html/scubadiving/.env
            echo "SCUBADIVING_APP_DATABASE_USER=$SCUBADIVING_APP_DATABASE_USER" >> /var/www/html/scubadiving/.env
            echo "SCUBADIVING_APP_DATABASE_PASSWORD=$SCUBADIVING_APP_DATABASE_PASSWORD" >> /var/www/html/scubadiving/.env
            echo "SECRET_KEY_BASE=$SECRET_KEY_BASE" >> /var/www/html/scubadiving/.env

            # Ensure the .env file is created successfully
            if [ ! -f /var/www/html/scubadiving/.env ]; then
              echo ".env file not created. Exiting."
              exit 1
            else
              echo ".env file created successfully."
              cat /var/www/html/scubadiving/.env
            fi

            # Build and start Docker containers with the generated .env file
            echo "Building Docker images and starting containers..."
            sudo docker-compose down || true
            sudo docker-compose up -d --build || { echo "Error: Docker build failed"; exit 1; }

            echo "Deployment complete."
          EOF
