name: Deploy Rails App with Nginx
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Build and Deploy Rails App
    runs-on: ubuntu-latest

    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: elviajero34
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Step 4: Build and push the Docker image
      - name: Build and Push Docker Image
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u elviajero34 -p $DOCKERHUB_PASSWORD
          docker buildx build \
            --platform linux/arm/v7 \
            --tag elviajero34/scubadiving-app:latest \
            --cache-from=type=registry,ref=elviajero34/scubadiving-app:latest \
            --push .

      # Step 5: Deploy to Raspberry Pi
      - name: Deploy to Raspberry Pi
        env:
          RASPBERRY_PI_USER: ${{ secrets.RASPBERRY_PI_USER }}
          RASPBERRY_PI_IP: ${{ secrets.RASPBERRY_PI_IP }}
          RASPBERRY_PI_PASSWORD: ${{ secrets.RASPBERRY_PI_PASSWORD }}
        run: |
          sshpass -p $RASPBERRY_PI_PASSWORD ssh -o ServerAliveInterval=120 -o ServerAliveCountMax=100 -o StrictHostKeyChecking=no $RASPBERRY_PI_USER@$RASPBERRY_PI_IP <<EOF
            set -e
            echo "Deploying application..."

            # Navigate to app directory
            cd /var/www/html/scubadiving

            # Pull the latest image from Docker Hub
            echo "Pulling the latest Docker image..."
            docker pull elviajero34/scubadiving-app:latest

            # Ensure Docker Compose is installed
            echo "Installing Docker Compose if not available..."
            if ! [ -x "$(command -v docker-compose)" ]; then
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-armv7" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Stop old containers and start new ones
            echo "Restarting containers..."
            docker-compose down --remove-orphans
            docker-compose up -d --build
            docker-compose run --rm certbot certonly --webroot --webroot-path=/var/lib/letsencrypt --email lucas.illiano@hotmail.com --agree-tos --no-eff-email -d scubadiving.nomadev.online


            # Run database migrations
            echo "Running database migrations..."
            docker-compose exec app bundle exec rake db:migrate
          EOF
